-- ----------------------------
-- 影约云业务表与菜单 MySQL 脚本
-- 执行顺序：先执行 RuoYi 基础脚本，再执行本脚本，最后执行 yy_cloud_codegen.sql
-- ----------------------------

create table if not exists yy_store (
    id             bigint(20)   not null                    comment '主键',
    tenant_id      varchar(20)  default '000000'            comment '租户编号',
    store_code     varchar(64)  not null                    comment '门店编码',
    store_name     varchar(128) not null                    comment '门店名称',
    status         char(1)      default '0'                 comment '营业状态',
    phone          varchar(32)  default ''                  comment '联系电话',
    address        varchar(255) default ''                  comment '门店地址',
    business_hours varchar(128) default ''                  comment '营业时间',
    sort           int          default 0                   comment '排序',
    create_dept    bigint(20)   default null                comment '创建部门',
    create_by      bigint(20)   default null                comment '创建者',
    create_time    datetime                                comment '创建时间',
    update_by      bigint(20)   default null                comment '更新者',
    update_time    datetime                                comment '更新时间',
    del_flag       char(1)      default '0'                 comment '删除标志',
    remark         varchar(500) default null                comment '备注',
    primary key (id),
    unique key uk_yy_store_code (tenant_id, store_code)
) engine=innodb comment='影约云门店';

create table if not exists yy_product (
    id                 bigint(20)    not null                 comment '主键',
    tenant_id          varchar(20)   default '000000'         comment '租户编号',
    store_id           bigint(20)    default null             comment '门店ID',
    product_type       varchar(32)   not null                 comment '产品类型',
    product_name       varchar(128)  not null                 comment '产品名称',
    price              decimal(10,2) default 0.00             comment '销售价',
    duration_minutes   int           default 0                comment '服务时长',
    selection_price    decimal(10,2) default 0.00             comment '选片单价',
    album_product_name varchar(128)  default ''               comment '入册产品',
    status             char(1)       default '0'              comment '状态',
    sort               int           default 0                comment '排序',
    create_dept        bigint(20)    default null             comment '创建部门',
    create_by          bigint(20)    default null             comment '创建者',
    create_time        datetime                              comment '创建时间',
    update_by          bigint(20)    default null             comment '更新者',
    update_time        datetime                              comment '更新时间',
    del_flag           char(1)       default '0'              comment '删除标志',
    remark             varchar(500)  default null             comment '备注',
    primary key (id),
    key idx_yy_product_store (tenant_id, store_id)
) engine=innodb comment='影约云产品';

create table if not exists yy_order (
    id                bigint(20)    not null                  comment '主键',
    tenant_id         varchar(20)   default '000000'          comment '租户编号',
    store_id          bigint(20)    not null                  comment '门店ID',
    order_no          varchar(64)   not null                  comment '订单编号',
    customer_name     varchar(64)   default ''                comment '客户姓名',
    customer_phone    varchar(32)   default ''                comment '客户手机号',
    source            varchar(32)   default 'LOCAL'           comment '订单来源',
    booking_method    varchar(32)   default 'MANUAL'          comment '预约方式',
    order_time        datetime                               comment '下单时间',
    arrival_time      datetime                               comment '到店时间',
    status            varchar(32)   default 'PENDING'         comment '订单状态',
    workstation_no    varchar(32)   default ''                comment '工位',
    external_order_id varchar(128)  default ''                comment '外部订单号',
    channel_type      varchar(32)   default ''                comment '渠道类型',
    total_amount_cent bigint(20)    default 0                 comment '订单总金额（分）',
    paid_amount_cent  bigint(20)    default 0                 comment '实付金额（分）',
    pay_status        varchar(32)   default 'UNPAID'          comment '支付状态',
    paid_time         datetime                               comment '支付时间',
    refund_status     varchar(32)   default ''                comment '退款状态',
    refund_amount_cent bigint(20)   default 0                 comment '退款金额（分）',
    external_product_id varchar(128) default ''               comment '外部商品ID',
    external_sku_id   varchar(128)  default ''                comment '外部SKU ID',
    external_poi_id   varchar(128)  default ''                comment '外部门店/POI ID',
    service_group_id  bigint(20)    default null              comment '服务组ID',
    inventory_slot_id bigint(20)    default null              comment '本地库存时段ID',
    slot_date         varchar(16)   default ''                comment '预约日期',
    slot_start_time   varchar(16)   default ''                comment '预约开始时间',
    slot_end_time     varchar(16)   default ''                comment '预约结束时间',
    inventory_status  varchar(32)   default ''                comment '库存状态',
    conflict_reason   varchar(255)  default ''                comment '库存冲突原因',
    order_attribute_json longtext                           comment '订单属性快照和值',
    create_dept       bigint(20)    default null              comment '创建部门',
    create_by         bigint(20)    default null              comment '创建者',
    create_time       datetime                               comment '创建时间',
    update_by         bigint(20)    default null              comment '更新者',
    update_time       datetime                               comment '更新时间',
    del_flag          char(1)       default '0'               comment '删除标志',
    remark            varchar(500)  default null              comment '备注',
    primary key (id),
    unique key uk_yy_order_no (tenant_id, order_no),
    key idx_yy_order_filter (tenant_id, store_id, source, booking_method, status)
) engine=innodb comment='影约云预约订单';

create table if not exists yy_photo_album (
    id               bigint(20)   not null                    comment '主键',
    tenant_id        varchar(20)  default '000000'            comment '租户编号',
    store_id         bigint(20)   not null                    comment '门店ID',
    order_id         bigint(20)   default null                comment '订单ID',
    album_name       varchar(128) not null                    comment '相册名称',
    customer_name    varchar(64)  default ''                  comment '客户姓名',
    customer_phone   varchar(32)  default ''                  comment '客户手机号',
    public_token     varchar(128) default ''                  comment '公开选片令牌',
    access_code      varchar(128) default ''                  comment '客户取片码',
    channel_type     varchar(32)  default 'H5'               comment '渠道类型',
    status           varchar(32)  default 'ACTIVE'           comment '相册状态',
    selection_status varchar(32)  default 'DRAFT'             comment '选片状态',
    douyin_order_id  varchar(128) default ''                  comment '抖音订单号',
    certificate_code varchar(128) default ''                  comment '抖音券码',
    book_id          varchar(128) default ''                  comment '抖音预约单ID',
    expire_time      datetime                                comment '过期时间',
    create_dept      bigint(20)   default null                comment '创建部门',
    create_by        bigint(20)   default null                comment '创建者',
    create_time      datetime                                comment '创建时间',
    update_by        bigint(20)   default null                comment '更新者',
    update_time      datetime                                comment '更新时间',
    del_flag         char(1)      default '0'                 comment '删除标志',
    remark           varchar(500) default null                comment '备注',
    primary key (id),
    key idx_yy_photo_album_order (tenant_id, order_id)
) engine=innodb comment='影约云相册';

create table if not exists yy_photo_asset (
    id          bigint(20)   not null                         comment '主键',
    tenant_id   varchar(20)  default '000000'                 comment '租户编号',
    store_id    bigint(20)   not null                         comment '门店ID',
    album_id    bigint(20)   not null                         comment '相册ID',
    file_name   varchar(255) not null                         comment '文件名',
    file_url    varchar(500) not null                         comment '文件地址',
    object_key  varchar(500) default ''                      comment 'OSS对象Key',
    thumbnail_object_key varchar(500) default ''             comment '缩略图OSS对象Key',
    sort        int          default 0                        comment '排序',
    is_selected char(1)      default '0'                      comment '是否已选',
    visible     char(1)      default '1'                      comment '客户可见',
    create_dept bigint(20)   default null                     comment '创建部门',
    create_by   bigint(20)   default null                     comment '创建者',
    create_time datetime                                     comment '创建时间',
    update_by   bigint(20)   default null                     comment '更新者',
    update_time datetime                                     comment '更新时间',
    del_flag    char(1)      default '0'                      comment '删除标志',
    object_key_active varchar(500)
        generated always as (
            case
                when del_flag = '0' and object_key is not null and trim(object_key) <> ''
                then object_key
                else null
            end
        ) stored                                               comment '有效OSS对象Key',
    remark      varchar(500) default null                     comment '备注',
    primary key (id),
    key idx_yy_photo_asset_album (tenant_id, album_id),
    unique key uk_yy_photo_asset_album_object_key_active (tenant_id, album_id, object_key_active),
    constraint ck_yy_photo_asset_visible_object_key check (del_flag = '1' or visible <> '1' or trim(coalesce(object_key, '')) <> '')
) engine=innodb comment='影约云底片';

alter table yy_photo_asset
    add column if not exists asset_type varchar(32) default 'RAW' comment 'resource type',
    add column if not exists rating int default 0 comment 'resource rating',
    add column if not exists file_size_bytes bigint(20) default 0 comment 'file size bytes';

create table if not exists yy_photo_tag (
    id          bigint(20)   not null                         comment 'primary key',
    tenant_id   varchar(20)  default '000000'                 comment 'tenant id',
    store_id    bigint(20)   not null                         comment 'store id',
    tag_name    varchar(64)  not null                         comment 'tag name',
    create_dept bigint(20)   default null                     comment 'create dept',
    create_by   bigint(20)   default null                     comment 'create by',
    create_time datetime                                     comment 'create time',
    update_by   bigint(20)   default null                     comment 'update by',
    update_time datetime                                     comment 'update time',
    del_flag    char(1)      default '0'                      comment 'delete flag',
    remark      varchar(500) default null                     comment 'remark',
    primary key (id),
    unique key uk_yy_photo_tag_store_name_flag (tenant_id, store_id, tag_name, del_flag),
    key idx_yy_photo_tag_store (tenant_id, store_id)
) engine=innodb comment='resource tags';

create table if not exists yy_photo_asset_tag (
    id          bigint(20)   not null                         comment 'primary key',
    tenant_id   varchar(20)  default '000000'                 comment 'tenant id',
    store_id    bigint(20)   not null                         comment 'store id',
    asset_id    bigint(20)   not null                         comment 'asset id',
    tag_id      bigint(20)   not null                         comment 'tag id',
    create_dept bigint(20)   default null                     comment 'create dept',
    create_by   bigint(20)   default null                     comment 'create by',
    create_time datetime                                     comment 'create time',
    update_by   bigint(20)   default null                     comment 'update by',
    update_time datetime                                     comment 'update time',
    del_flag    char(1)      default '0'                      comment 'delete flag',
    remark      varchar(500) default null                     comment 'remark',
    primary key (id),
    unique key uk_yy_photo_asset_tag_relation_flag (tenant_id, asset_id, tag_id, del_flag),
    key idx_yy_photo_asset_tag_asset (tenant_id, asset_id),
    key idx_yy_photo_asset_tag_tag (tenant_id, tag_id)
) engine=innodb comment='resource tag relations';

create table if not exists yy_photo_access_log (
    id            bigint(20)   not null                      comment '主键',
    tenant_id     varchar(20)  default '000000'              comment '租户编号',
    store_id      bigint(20)   default null                  comment '门店ID',
    album_id      bigint(20)   default null                  comment '相册ID',
    asset_id      bigint(20)   default null                  comment '照片ID',
    customer_phone varchar(32) default ''                    comment '客户手机号',
    platform      varchar(32)  default 'H5'                  comment '平台',
    action        varchar(64)  default ''                    comment '动作',
    ip            varchar(64)  default ''                    comment 'IP',
    success       char(1)      default '1'                   comment '是否成功',
    create_dept   bigint(20)   default null                  comment '创建部门',
    create_by     bigint(20)   default null                  comment '创建者',
    create_time   datetime                                comment '创建时间',
    update_by     bigint(20)   default null                  comment '更新者',
    update_time   datetime                                comment '更新时间',
    del_flag      char(1)      default '0'                   comment '删除标志',
    remark        varchar(500) default null                  comment '备注',
    primary key (id),
    key idx_yy_photo_access_log (tenant_id, album_id, action, create_time)
) engine=innodb comment='客户取片访问日志';

create table if not exists yy_photo_verify_code (
    id            bigint(20)   not null                      comment '主键',
    tenant_id     varchar(20)  default '000000'              comment '租户编号',
    phone         varchar(32)  default ''                    comment '手机号',
    verify_code   varchar(16)  default ''                    comment '验证码',
    scene         varchar(32)  default 'PHOTO_PICKUP'        comment '场景',
    platform      varchar(32)  default 'H5'                  comment '平台',
    expire_time   datetime                                comment '过期时间',
    used_time     datetime                                comment '使用时间',
    status        varchar(32)  default 'CREATED'             comment '状态',
    ip            varchar(64)  default ''                    comment 'IP',
    create_dept   bigint(20)   default null                  comment '创建部门',
    create_by     bigint(20)   default null                  comment '创建者',
    create_time   datetime                                comment '创建时间',
    update_by     bigint(20)   default null                  comment '更新者',
    update_time   datetime                                comment '更新时间',
    del_flag      char(1)      default '0'                   comment '删除标志',
    remark        varchar(500) default null                  comment '备注',
    primary key (id),
    key idx_yy_photo_verify_code (tenant_id, phone, scene, status, expire_time)
) engine=innodb comment='客户取片验证码';

create table if not exists yy_channel_plugin (
    id             bigint(20)   not null                      comment '主键',
    tenant_id      varchar(20)  default '000000'              comment '租户编号',
    channel_type   varchar(32)  not null                      comment '渠道类型',
    plugin_name    varchar(128) not null                      comment '插件名称',
    enabled        char(1)      default '0'                   comment '是否启用',
    auth_status    varchar(32)  default 'UNOPENED'            comment '授权状态',
    open_tip       varchar(255) default ''                    comment '未开通提示',
    last_sync_time datetime                                  comment '最后同步时间',
    create_dept    bigint(20)   default null                  comment '创建部门',
    create_by      bigint(20)   default null                  comment '创建者',
    create_time    datetime                                  comment '创建时间',
    update_by      bigint(20)   default null                  comment '更新者',
    update_time    datetime                                  comment '更新时间',
    del_flag       char(1)      default '0'                   comment '删除标志',
    remark         varchar(500) default null                  comment '备注',
    primary key (id),
    unique key uk_yy_channel_plugin (tenant_id, channel_type)
) engine=innodb comment='影约云渠道插件';

create table if not exists yy_channel_account (
    id                bigint(20)   not null                   comment '主键',
    tenant_id         varchar(20)  default '000000'           comment '租户编号',
    store_id          bigint(20)   default null               comment '门店ID',
    channel_type      varchar(32)  not null                   comment '渠道类型',
    account_name      varchar(128) default ''                 comment '授权账号',
    app_key           varchar(128) default ''                 comment '应用Key',
    app_secret_enc    varchar(500) default ''                 comment '加密应用密钥',
    service_id        varchar(128) default ''                 comment '服务ID',
    service_mode_id   varchar(128) default ''                 comment '服务模式ID',
    service_market_app_id varchar(128) default ''             comment '服务市场应用ID',
    service_market_path   varchar(500) default ''             comment '服务市场跳转路径',
    test_open_id      varchar(128) default ''                 comment '测试用户OpenID',
    webhook_url       varchar(500) default ''                 comment 'Webhook回调地址',
    access_token_enc  varchar(500) default ''                 comment '加密访问令牌',
    refresh_token_enc varchar(500) default ''                 comment '加密刷新令牌',
    expires_at        datetime                               comment '过期时间',
    status            varchar(32)  default 'UNAUTHORIZED'     comment '授权状态',
    create_dept       bigint(20)   default null               comment '创建部门',
    create_by         bigint(20)   default null               comment '创建者',
    create_time       datetime                               comment '创建时间',
    update_by         bigint(20)   default null               comment '更新者',
    update_time       datetime                               comment '更新时间',
    del_flag          char(1)      default '0'                comment '删除标志',
    remark            varchar(500) default null               comment '备注',
    primary key (id),
    key idx_yy_channel_account (tenant_id, store_id, channel_type)
) engine=innodb comment='影约云渠道授权账号';

create table if not exists yy_channel_product_mapping (
    id                  bigint(20)   not null                 comment '主键',
    tenant_id           varchar(20)  default '000000'         comment '租户编号',
    store_id            bigint(20)   default null             comment '门店ID',
    product_id          bigint(20)   not null                 comment '本地产品ID',
    channel_type        varchar(32)  not null                 comment '渠道类型',
    external_product_id varchar(128) default ''               comment '外部商品ID',
    external_sku_id     varchar(128) default ''               comment '外部SKU',
    external_poi_id     varchar(128) default ''               comment '外部门店POI',
    landing_url         varchar(500) default ''               comment '真实下单入口链接',
    landing_path        varchar(500) default ''               comment '小程序/抖音路径',
    external_name       varchar(255) default ''               comment '外部商品名',
    mapping_status      varchar(32)  default 'UNMAPPED'       comment '映射状态',
    create_dept         bigint(20)   default null             comment '创建部门',
    create_by           bigint(20)   default null             comment '创建者',
    create_time         datetime                             comment '创建时间',
    update_by           bigint(20)   default null             comment '更新者',
    update_time         datetime                             comment '更新时间',
    del_flag            char(1)      default '0'              comment '删除标志',
    remark              varchar(500) default null             comment '备注',
    primary key (id),
    key idx_yy_channel_product (tenant_id, channel_type, product_id)
) engine=innodb comment='影约云渠道商品映射';

create table if not exists yy_channel_order_mapping (
    id                bigint(20)   not null                   comment '主键',
    tenant_id         varchar(20)  default '000000'           comment '租户编号',
    store_id          bigint(20)   default null               comment '门店ID',
    order_id          bigint(20)   default null               comment '本地订单ID',
    channel_type      varchar(32)  not null                   comment '渠道类型',
    external_order_id varchar(128) not null                   comment '外部订单号',
    external_status   varchar(64)  default ''                 comment '外部状态',
    sync_status       varchar(32)  default 'PENDING'          comment '同步状态',
    raw_payload       longtext                                comment '原始报文',
    create_dept       bigint(20)   default null               comment '创建部门',
    create_by         bigint(20)   default null               comment '创建者',
    create_time       datetime                               comment '创建时间',
    update_by         bigint(20)   default null               comment '更新者',
    update_time       datetime                               comment '更新时间',
    del_flag          char(1)      default '0'                comment '删除标志',
    remark            varchar(500) default null               comment '备注',
    primary key (id),
    unique key uk_yy_channel_order (tenant_id, channel_type, external_order_id)
) engine=innodb comment='影约云渠道订单映射';

create table if not exists yy_channel_sync_log (
    id            bigint(20)   not null                       comment '主键',
    tenant_id     varchar(20)  default '000000'               comment '租户编号',
    store_id      bigint(20)   default null                   comment '门店ID',
    channel_type  varchar(32)  not null                       comment '渠道类型',
    api_name      varchar(128) not null                       comment '接口名',
    request_id    varchar(128) default ''                     comment '请求ID',
    success       char(1)      default '0'                    comment '是否成功',
    error_message longtext                                    comment '错误信息',
    duration_ms   bigint(20)   default 0                      comment '耗时毫秒',
    retryable     char(1)      default '0'                    comment '是否可重试',
    create_dept   bigint(20)   default null                   comment '创建部门',
    create_by     bigint(20)   default null                   comment '创建者',
    create_time   datetime                                   comment '创建时间',
    update_by     bigint(20)   default null                   comment '更新者',
    update_time   datetime                                   comment '更新时间',
    del_flag      char(1)      default '0'                    comment '删除标志',
    remark        varchar(500) default null                   comment '备注',
    primary key (id),
     key idx_yy_channel_log (tenant_id, channel_type, api_name, create_time)
) engine=innodb comment='影约云渠道同步日志';

create table if not exists yy_channel_inventory_slot (
    id              bigint(20)   not null                   comment '主键',
    tenant_id       varchar(20)  default '000000'           comment '租户编号',
    store_id        bigint(20)   default null               comment '门店ID',
    channel_type    varchar(32)  not null                   comment '渠道类型',
    account_id      varchar(128) default ''                 comment '外部商家账号ID',
    poi_id          varchar(128) default ''                 comment '外部门店POI',
    sku_id          varchar(128) default ''                 comment '外部SKU',
    sku_out_id      varchar(128) default ''                 comment '外部三方SKU',
    biz_date        varchar(16)  default ''                 comment '库存日期',
    start_time      varchar(16)  default ''                 comment '开始时间',
    end_time        varchar(16)  default ''                 comment '结束时间',
    available_stock int          default 0                  comment '可用库存',
    sync_status     varchar(32)  default 'PENDING'          comment '同步状态',
    last_log_id     varchar(128) default ''                 comment '最近logid',
    raw_payload     longtext                                comment '原始报文',
    create_dept     bigint(20)   default null               comment '创建部门',
    create_by       bigint(20)   default null               comment '创建者',
    create_time     datetime                               comment '创建时间',
    update_by       bigint(20)   default null               comment '更新者',
    update_time     datetime                               comment '更新时间',
    del_flag        char(1)      default '0'                comment '删除标志',
    remark          varchar(500) default null               comment '备注',
    primary key (id),
    key idx_yy_channel_inventory_slot (tenant_id, channel_type, poi_id, sku_id, sku_out_id, biz_date, start_time)
) engine=innodb comment='影约云渠道预约库存槽';

create table if not exists yy_service_group (
    id               bigint(20)   not null                   comment '主键',
    tenant_id        varchar(20)  default '000000'           comment '租户编号',
    store_id         bigint(20)   not null                   comment '门店ID',
    group_code       varchar(64)  not null                   comment '服务组编码',
    group_name       varchar(128) not null                   comment '服务组名称',
    capacity         int          default 1                  comment '默认容量',
    duration_minutes int          default 30                 comment '默认时长',
    service_mode     varchar(32)  default 'HORIZONTAL'       comment '服务模式',
    status           char(1)      default '0'                comment '状态',
    sort             int          default 0                  comment '排序',
    create_dept      bigint(20)   default null               comment '创建部门',
    create_by        bigint(20)   default null               comment '创建者',
    create_time      datetime                               comment '创建时间',
    update_by        bigint(20)   default null               comment '更新者',
    update_time      datetime                               comment '更新时间',
    del_flag         char(1)      default '0'                comment '删除标志',
    remark           varchar(500) default null               comment '备注',
    primary key (id),
    unique key uk_yy_service_group (tenant_id, store_id, group_code)
) engine=innodb comment='影约云服务组';

create table if not exists yy_order_attribute_template (
    id            bigint(20)   not null                      comment '主键',
    tenant_id     varchar(20)  default '000000'             comment '租户编号',
    store_id      bigint(20)   not null                      comment '门店ID',
    field_code    varchar(64)  not null                      comment '字段编码',
    field_label   varchar(64)  not null                      comment '字段名称',
    field_type    varchar(32)  not null                      comment '字段类型',
    required      char(1)      default '0'                   comment '是否必填',
    options_json  longtext                                  comment '选项JSON',
    sort          int          default 0                     comment '排序',
    status        varchar(32)  default 'ACTIVE'              comment '状态',
    create_dept   bigint(20)   default null                  comment '创建部门',
    create_by     bigint(20)   default null                  comment '创建者',
    create_time   datetime                                  comment '创建时间',
    update_by     bigint(20)   default null                  comment '更新者',
    update_time   datetime                                  comment '更新时间',
    del_flag      char(1)      default '0'                   comment '删除标志',
    remark        varchar(500) default null                  comment '备注',
    primary key (id),
    unique key uk_yy_order_attr_tpl (tenant_id, store_id, field_code)
) engine=innodb comment='影约云订单属性模板';

alter table yy_order
    add column if not exists order_attribute_json longtext comment '订单属性快照和值';

alter table yy_service_group
    add column if not exists service_mode varchar(32) default 'HORIZONTAL' comment '服务模式';

create table if not exists yy_schedule_rule (
    id               bigint(20)   not null                   comment '主键',
    tenant_id        varchar(20)  default '000000'           comment '租户编号',
    store_id         bigint(20)   not null                   comment '门店ID',
    service_group_id bigint(20)   not null                   comment '服务组ID',
    weekday          int          not null                   comment '星期几',
    start_time       varchar(16)  not null                   comment '开始时间',
    end_time         varchar(16)  not null                   comment '结束时间',
    capacity         int          default 1                  comment '容量',
    enabled          char(1)      default '1'                comment '是否启用',
    create_dept      bigint(20)   default null               comment '创建部门',
    create_by        bigint(20)   default null               comment '创建者',
    create_time      datetime                               comment '创建时间',
    update_by        bigint(20)   default null               comment '更新者',
    update_time      datetime                               comment '更新时间',
    del_flag         char(1)      default '0'                comment '删除标志',
    remark           varchar(500) default null               comment '备注',
    primary key (id),
    key idx_yy_schedule_rule (tenant_id, store_id, service_group_id, weekday)
) engine=innodb comment='影约云预约排期规则';

create table if not exists yy_schedule_exception_rule (
    id               bigint(20)   not null,
    tenant_id        varchar(20)  default '000000',
    store_id         bigint(20)   not null,
    service_group_id bigint(20)   default null,
    start_date       varchar(16)  not null,
    end_date         varchar(16)  not null,
    start_time       varchar(16)  not null,
    end_time         varchar(16)  not null,
    action_type      varchar(32)  not null,
    capacity         int          default null,
    reason           varchar(500) default '',
    status           varchar(32)  default 'ACTIVE',
    approval_id      bigint(20)   default null,
    create_dept      bigint(20)   default null,
    create_by        bigint(20)   default null,
    create_time      datetime,
    update_by        bigint(20)   default null,
    update_time      datetime,
    del_flag         char(1)      default '0',
    remark           varchar(500) default null,
    primary key (id),
    key idx_yy_schedule_exception_rule_scope (tenant_id, store_id, service_group_id, start_date, end_date, status)
) engine=innodb comment='yy schedule exception rule';

create table if not exists yy_risk_approval (
    id                bigint(20)   not null,
    tenant_id         varchar(20)  default '000000',
    store_id          bigint(20)   default null,
    business_type     varchar(64)  not null,
    business_id       bigint(20)   default null,
    business_no       varchar(128) default '',
    status            varchar(32)  default 'PENDING',
    title             varchar(128) default '',
    reason            varchar(500) default '',
    payload_json      longtext,
    applicant_user_id bigint(20)   default null,
    applicant_name    varchar(64)  default '',
    approver_user_id  bigint(20)   default null,
    approver_name     varchar(64)  default '',
    approve_time      datetime,
    reject_reason     varchar(500) default '',
    result_summary    varchar(500) default '',
    create_dept       bigint(20)   default null,
    create_by         bigint(20)   default null,
    create_time       datetime,
    update_by         bigint(20)   default null,
    update_time       datetime,
    del_flag          char(1)      default '0',
    remark            varchar(500) default null,
    primary key (id),
    key idx_yy_risk_approval_status (tenant_id, status, business_type, create_time),
    key idx_yy_risk_approval_business (tenant_id, business_type, business_id)
) engine=innodb comment='yy risk approval';

create table if not exists yy_entitlement_reservation (
    id                 bigint(20)   not null,
    tenant_id          varchar(20)  default '000000',
    store_id           bigint(20)   default null,
    customer_id        bigint(20)   not null,
    order_id           bigint(20)   default null,
    reservation_no     varchar(64)  not null,
    reservation_type   varchar(32)  default 'BENEFIT',
    target_type        varchar(32)  default 'MEMBER_ASSET',
    target_snapshot    varchar(255) default '',
    quantity           decimal(12,2) default 1.00,
    reservation_amount decimal(12,2) default 0.00,
    status             varchar(32)  default 'RESERVED',
    idempotency_key    varchar(64)  default '',
    expire_time        datetime,
    released_time      datetime,
    execution_mode     varchar(32)  default 'SCAFFOLD',
    create_dept        bigint(20)   default null,
    create_by          bigint(20)   default null,
    create_time        datetime,
    update_by          bigint(20)   default null,
    update_time        datetime,
    del_flag           char(1)      default '0',
    remark             varchar(500) default null,
    primary key (id),
    unique key uk_yy_entitlement_reservation_no (tenant_id, reservation_no),
    key idx_yy_entitlement_reservation_scope (tenant_id, customer_id, order_id, status, create_time)
) engine=innodb comment='yy entitlement reservation scaffold';

create table if not exists yy_composite_payment_order (
    id                  bigint(20)   not null,
    tenant_id           varchar(20)  default '000000',
    store_id            bigint(20)   default null,
    customer_id         bigint(20)   not null,
    order_id            bigint(20)   default null,
    composite_no        varchar(64)  not null,
    total_amount        decimal(12,2) default 0.00,
    external_amount     decimal(12,2) default 0.00,
    stored_value_amount decimal(12,2) default 0.00,
    cash_amount         decimal(12,2) default 0.00,
    discount_amount     decimal(12,2) default 0.00,
    waive_amount        decimal(12,2) default 0.00,
    status              varchar(32)  default 'DRAFT',
    settle_status       varchar(32)  default 'PENDING',
    execution_mode      varchar(32)  default 'SCAFFOLD',
    create_dept         bigint(20)   default null,
    create_by           bigint(20)   default null,
    create_time         datetime,
    update_by           bigint(20)   default null,
    update_time         datetime,
    del_flag            char(1)      default '0',
    remark              varchar(500) default null,
    primary key (id),
    unique key uk_yy_composite_payment_no (tenant_id, composite_no),
    key idx_yy_composite_payment_scope (tenant_id, customer_id, order_id, status, create_time)
) engine=innodb comment='yy composite payment scaffold';

create table if not exists yy_stored_value_consume_order (
    id               bigint(20)   not null,
    tenant_id        varchar(20)  default '000000',
    store_id         bigint(20)   default null,
    customer_id      bigint(20)   not null,
    order_id         bigint(20)   default null,
    consume_no       varchar(64)  not null,
    consume_amount   decimal(12,2) default 0.00,
    balance_snapshot decimal(12,2) default 0.00,
    status           varchar(32)  default 'FROZEN',
    reversal_status  varchar(32)  default 'NONE',
    execution_mode   varchar(32)  default 'SCAFFOLD',
    confirmed_time   datetime,
    create_dept      bigint(20)   default null,
    create_by        bigint(20)   default null,
    create_time      datetime,
    update_by        bigint(20)   default null,
    update_time      datetime,
    del_flag         char(1)      default '0',
    remark           varchar(500) default null,
    primary key (id),
    unique key uk_yy_stored_value_consume_no (tenant_id, consume_no),
    key idx_yy_stored_value_consume_scope (tenant_id, customer_id, order_id, status, create_time)
) engine=innodb comment='yy stored value consume scaffold';

create table if not exists yy_member_withdraw_order (
    id                bigint(20)   not null,
    tenant_id         varchar(20)  default '000000',
    store_id          bigint(20)   default null,
    customer_id       bigint(20)   not null,
    withdraw_no       varchar(64)  not null,
    withdraw_amount   decimal(12,2) default 0.00,
    balance_snapshot  decimal(12,2) default 0.00,
    approval_id       bigint(20)   default null,
    account_name      varchar(64)  default '',
    account_no_masked varchar(64)  default '',
    channel_type      varchar(32)  default 'BANK_TRANSFER',
    status            varchar(32)  default 'PENDING_APPROVAL',
    execution_mode    varchar(32)  default 'SCAFFOLD',
    paid_time         datetime,
    create_dept       bigint(20)   default null,
    create_by         bigint(20)   default null,
    create_time       datetime,
    update_by         bigint(20)   default null,
    update_time       datetime,
    del_flag          char(1)      default '0',
    remark            varchar(500) default null,
    primary key (id),
    unique key uk_yy_member_withdraw_no (tenant_id, withdraw_no),
    key idx_yy_member_withdraw_scope (tenant_id, customer_id, status, create_time)
) engine=innodb comment='yy member withdraw scaffold';

create table if not exists yy_employee (
    id            bigint(20)   not null                      comment '主键',
    tenant_id     varchar(20)  default '000000'              comment '租户编号',
    store_id      bigint(20)   not null                      comment '门店ID',
    user_id       bigint(20)   default null                  comment '系统用户ID',
    employee_no   varchar(64)  not null                      comment '员工编号',
    employee_name varchar(64)  not null                      comment '员工姓名',
    mobile        varchar(32)  default ''                    comment '手机号',
    role_type     varchar(32)  default 'STAFF'               comment '岗位类型',
    skill_tags    varchar(255) default ''                    comment '技能标签',
    status        char(1)      default '0'                   comment '状态',
    sort          int          default 0                     comment '排序',
    create_dept   bigint(20)   default null                  comment '创建部门',
    create_by     bigint(20)   default null                  comment '创建者',
    create_time   datetime                                  comment '创建时间',
    update_by     bigint(20)   default null                  comment '更新者',
    update_time   datetime                                  comment '更新时间',
    del_flag      char(1)      default '0'                   comment '删除标志',
    remark        varchar(500) default null                  comment '备注',
    primary key (id),
    unique key uk_yy_employee_no (tenant_id, employee_no)
) engine=innodb comment='影约云员工';

create table if not exists yy_customer (
    id                bigint(20)    not null                 comment '主键',
    tenant_id         varchar(20)   default '000000'         comment '租户编号',
    customer_name     varchar(64)   not null                 comment '客户姓名',
    mobile            varchar(32)   not null                 comment '手机号',
    gender            char(1)       default '0'              comment '性别',
    birthday          date                                  comment '生日',
    source            varchar(32)   default 'LOCAL'          comment '来源',
    member_level      varchar(32)   default 'NORMAL'         comment '会员等级',
    total_order_count int           default 0                comment '订单数',
    total_spend       decimal(12,2) default 0.00             comment '累计消费',
    last_order_time   datetime                              comment '最近订单时间',
    tags              varchar(255)  default ''               comment '客户标签',
    create_dept       bigint(20)    default null             comment '创建部门',
    create_by         bigint(20)    default null             comment '创建者',
    create_time       datetime                              comment '创建时间',
    update_by         bigint(20)    default null             comment '更新者',
    update_time       datetime                              comment '更新时间',
    del_flag          char(1)       default '0'              comment '删除标志',
    remark            varchar(500)  default null             comment '备注',
    primary key (id),
    unique key uk_yy_customer_mobile (tenant_id, mobile)
) engine=innodb comment='影约云客户';

create table if not exists yy_notification_template (
    id                   bigint(20)    not null              comment '主键',
    tenant_id            varchar(20)   default '000000'      comment '租户编号',
    template_code        varchar(64)   not null              comment '模板编码',
    scene                varchar(64)   not null              comment '业务场景',
    channel_type         varchar(32)   not null              comment '通知渠道',
    title                varchar(128)  default ''            comment '标题',
    content              varchar(1000) not null              comment '模板内容',
    provider_template_id varchar(128)  default ''            comment '服务商模板ID',
    enabled              char(1)       default '1'           comment '是否启用',
    create_dept          bigint(20)    default null          comment '创建部门',
    create_by            bigint(20)    default null          comment '创建者',
    create_time          datetime                           comment '创建时间',
    update_by            bigint(20)    default null          comment '更新者',
    update_time          datetime                           comment '更新时间',
    del_flag             char(1)       default '0'           comment '删除标志',
    remark               varchar(500)  default null          comment '备注',
    primary key (id),
    unique key uk_yy_notice_template (tenant_id, template_code)
) engine=innodb comment='影约云通知模板';

create table if not exists yy_notification_log (
    id            bigint(20)   not null                      comment '主键',
    tenant_id     varchar(20)  default '000000'              comment '租户编号',
    store_id      bigint(20)   default null                  comment '门店ID',
    order_id      bigint(20)   default null                  comment '订单ID',
    customer_id   bigint(20)   default null                  comment '客户ID',
    template_id   bigint(20)   default null                  comment '模板ID',
    channel_type  varchar(32)  not null                      comment '通知渠道',
    receiver      varchar(128) not null                      comment '接收人',
    send_status   varchar(32)  default 'PENDING'             comment '发送状态',
    request_id    varchar(128) default ''                    comment '请求ID',
    error_message longtext                                   comment '错误信息',
    sent_time     datetime                                  comment '发送时间',
    raw_payload   longtext                                  comment '原始报文',
    create_dept   bigint(20)   default null                  comment '创建部门',
    create_by     bigint(20)   default null                  comment '创建者',
    create_time   datetime                                  comment '创建时间',
    update_by     bigint(20)   default null                  comment '更新者',
    update_time   datetime                                  comment '更新时间',
    del_flag      char(1)      default '0'                   comment '删除标志',
    remark        varchar(500) default null                  comment '备注',
    primary key (id),
    key idx_yy_notice_log (tenant_id, channel_type, send_status, create_time)
) engine=innodb comment='影约云通知日志';

create table if not exists yy_report_snapshot (
    id              bigint(20)    not null                   comment '主键',
    tenant_id       varchar(20)   default '000000'           comment '租户编号',
    store_id        bigint(20)    default null               comment '门店ID',
    report_date     date          not null                   comment '报表日期',
    report_type     varchar(32)   default 'DAILY'            comment '报表类型',
    order_total     int           default 0                  comment '订单数',
    arrived_total   int           default 0                  comment '到店数',
    completed_total int           default 0                  comment '完成数',
    revenue_total   decimal(12,2) default 0.00               comment '收入',
    selection_total decimal(12,2) default 0.00               comment '选片收入',
    source_summary  json                                     comment '来源汇总',
    create_dept     bigint(20)    default null               comment '创建部门',
    create_by       bigint(20)    default null               comment '创建者',
    create_time     datetime                                comment '创建时间',
    update_by       bigint(20)    default null               comment '更新者',
    update_time     datetime                                comment '更新时间',
    del_flag        char(1)       default '0'                comment '删除标志',
    remark          varchar(500)  default null               comment '备注',
    primary key (id),
    key idx_yy_report_snapshot (tenant_id, store_id, report_date, report_type)
) engine=innodb comment='影约云报表快照';

create table if not exists yy_async_task (
    id             bigint(20)   not null                      comment 'primary key',
    tenant_id      varchar(20)  default '000000'              comment 'tenant id',
    store_id       bigint(20)   default null                  comment 'store id',
    task_no        varchar(64)  not null                      comment 'task number',
    task_type      varchar(64)  not null                      comment 'task type',
    task_name      varchar(128) default ''                    comment 'task name',
    queue_name     varchar(64)  default ''                    comment 'queue name',
    status         varchar(32)  default 'PENDING'             comment 'task status',
    run_status     varchar(32)  default ''                    comment 'run status',
    business_type  varchar(64)  default ''                    comment 'business type',
    business_id    bigint(20)   default null                  comment 'business id',
    date_from      varchar(16)  default ''                    comment 'date from',
    date_to        varchar(16)  default ''                    comment 'date to',
    download_url   varchar(512) default ''                    comment 'download url',
    oss_id         bigint(20)   default null                  comment 'oss id',
    file_name      varchar(255) default ''                    comment 'file name',
    content_type   varchar(128) default ''                    comment 'content type',
    file_size_bytes bigint(20)  default 0                     comment 'file size bytes',
    payload_json   longtext                                   comment 'task payload json',
    started_time   datetime                                  comment 'started time',
    finished_time  datetime                                  comment 'finished time',
    expire_time    datetime                                  comment 'expire time',
    retry_count    int          default 0                     comment 'retry count',
    max_retry_count int         default 3                     comment 'max retry count',
    next_retry_time datetime                                 comment 'next retry time',
    claimed_by     varchar(128) default ''                    comment 'claimed by',
    claim_expire_time datetime                               comment 'claim expire time',
    error_message  varchar(512) default ''                    comment 'error message',
    audit_note     varchar(512) default ''                    comment 'audit note',
    remark         varchar(512) default ''                    comment 'remark',
    create_dept    bigint(20)   default null                  comment 'create dept',
    create_by      bigint(20)   default null                  comment 'create by',
    create_time    datetime                                  comment 'create time',
    update_by      bigint(20)   default null                  comment 'update by',
    update_time    datetime                                  comment 'update time',
    del_flag       char(1)      default '0'                   comment 'delete flag',
    primary key (id),
    unique key uk_yy_async_task_no (tenant_id, task_no),
    key idx_yy_async_task_type_status (tenant_id, task_type, status, create_time),
    key idx_yy_async_task_store_time (tenant_id, store_id, create_time)
) engine=innodb comment='yingyue async task ledger';

alter table yy_async_task
    add column if not exists oss_id bigint(20) default null comment 'oss id',
    add column if not exists file_name varchar(255) default '' comment 'file name',
    add column if not exists content_type varchar(128) default '' comment 'content type',
    add column if not exists file_size_bytes bigint(20) default 0 comment 'file size bytes',
    add column if not exists payload_json longtext comment 'task payload json',
    add column if not exists retry_count int default 0 comment 'retry count',
    add column if not exists max_retry_count int default 3 comment 'max retry count',
    add column if not exists next_retry_time datetime comment 'next retry time',
    add column if not exists claimed_by varchar(128) default '' comment 'claimed by',
    add column if not exists claim_expire_time datetime comment 'claim expire time';

create table if not exists yy_mobile_channel_config (
    id             bigint(20)   not null                     comment '主键',
    tenant_id      varchar(20)  default '000000'             comment '租户编号',
    channel_type   varchar(32)  not null                     comment '端类型',
    channel_name   varchar(128) not null                     comment '端名称',
    app_id         varchar(128) default ''                   comment '应用ID',
    app_secret_enc varchar(500) default ''                   comment '加密应用密钥',
    callback_url   varchar(500) default ''                   comment '回调地址',
    enabled        char(1)      default '0'                  comment '是否启用',
    sdk_status     varchar(32)  default 'PENDING'            comment 'SDK状态',
    create_dept    bigint(20)   default null                 comment '创建部门',
    create_by      bigint(20)   default null                 comment '创建者',
    create_time    datetime                                 comment '创建时间',
    update_by      bigint(20)   default null                 comment '更新者',
    update_time    datetime                                 comment '更新时间',
    del_flag       char(1)      default '0'                  comment '删除标志',
    remark         varchar(500) default null                 comment '备注',
    primary key (id),
    unique key uk_yy_mobile_channel (tenant_id, channel_type)
) engine=innodb comment='影约云多端入口配置';

insert ignore into sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query_param, is_frame, is_cache, menu_type, visible, status, perms, icon, create_dept, create_by, create_time, update_by, update_time, remark)
values
(6200, '影约云', 0, 6, 'yy', null, '', 1, 0, 'M', '0', '0', null, 'dashboard', 103, 1, sysdate(), null, null, '影约云业务目录'),
(6201, '预约概况', 6200, 1, 'dashboard', 'yy/dashboard/index', '', 1, 0, 'C', '0', '0', 'yy:dashboard:list', 'chart', 103, 1, sysdate(), null, null, '预约概况'),
(6202, '预约订单', 6200, 2, 'order', 'yy/order/index', '', 1, 0, 'C', '0', '0', 'yy:order:list', 'list', 103, 1, sysdate(), null, null, '预约订单列表'),
(6203, '门店管理', 6200, 3, 'store', 'yy/store/index', '', 1, 0, 'C', '0', '0', 'yy:store:list', 'build', 103, 1, sysdate(), null, null, '门店管理'),
(6204, '产品管理', 6200, 4, 'product', 'yy/product/index', '', 1, 0, 'C', '0', '0', 'yy:product:list', 'shopping', 103, 1, sysdate(), null, null, '产品与选片配置'),
(6205, '客片选片', 6200, 5, 'photo', 'yy/photo/index', '', 1, 0, 'C', '0', '0', 'yy:photo:list', 'image', 103, 1, sysdate(), null, null, '客片与底片列表'),
(6206, '渠道插件', 6200, 6, 'channel', 'yy/channel/index', '', 1, 0, 'C', '0', '0', 'yy:channel:list', 'link', 103, 1, sysdate(), null, null, '渠道插件总览'),
(6207, '抖音产品', 6200, 7, 'channel-douyin', 'yy/channel/douyin/index', '', 1, 0, 'C', '0', '0', 'yy:channel:douyin', 'guide', 103, 1, sysdate(), null, null, '抖音产品插件'),
(6208, '美团产品', 6200, 8, 'channel-meituan', 'yy/channel/meituan/index', '', 1, 0, 'C', '0', '0', 'yy:channel:meituan', 'guide', 103, 1, sysdate(), null, null, '美团产品插件'),
(6209, '微信生态', 6200, 9, 'wechat', 'yy/wechat/index', '', 1, 0, 'C', '0', '0', 'yy:wechat:list', 'message', 103, 1, sysdate(), null, null, '微信公众号、小程序、支付、企微客户联系'),
(6260, '抖音来客', 6200, 10, 'channel-life', 'yy/channel/life/index', '', 1, 0, 'C', '0', '0', 'yy:channel:life', 'briefcase', 103, 1, sysdate(), null, null, '抖音来客生活服务团购订单'),
(6250, '企业结构', 6200, 10, 'enterprise', 'yy/enterprise/index', '', 1, 0, 'C', '0', '0', 'yy:enterprise:list', 'tree', 103, 1, sysdate(), null, null, '企业版模块结构总览'),
(6251, '预约配置', 6200, 11, 'booking-config', 'yy/booking-config/index', '', 1, 0, 'C', '0', '0', 'yy:bookingConfig:list', 'date', 103, 1, sysdate(), null, null, '服务组与预约时段规则'),
(6252, '员工管理', 6200, 12, 'employee', 'yy/employee/index', '', 1, 0, 'C', '0', '0', 'yy:employee:list', 'peoples', 103, 1, sysdate(), null, null, '员工台账与门店岗位'),
(6253, '客户管理', 6200, 13, 'customer', 'yy/customer/index', '', 1, 0, 'C', '0', '0', 'yy:customer:list', 'user', 103, 1, sysdate(), null, null, '客户档案与消费记录'),
(6254, '通知中心', 6200, 14, 'notification', 'yy/notification/index', '', 1, 0, 'C', '0', '0', 'yy:notification:list', 'message', 103, 1, sysdate(), null, null, '通知模板与发送日志'),
(6255, '经营报表', 6200, 15, 'report', 'yy/report/index', '', 1, 0, 'C', '0', '0', 'yy:report:list', 'chart', 103, 1, sysdate(), null, null, '门店、渠道、选片经营报表'),
(6256, '多端预约', 6200, 16, 'mobile', 'yy/mobile/index', '', 1, 0, 'C', '0', '0', 'yy:mobile:list', 'phone', 103, 1, sysdate(), null, null, 'H5、小程序、App 预约入口配置');

insert ignore into sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query_param, is_frame, is_cache, menu_type, visible, status, perms, icon, create_dept, create_by, create_time, update_by, update_time, remark)
values
(6210, '订单查询', 6202, 1, '#', '', '', 1, 0, 'F', '0', '0', 'yy:order:list', '#', 103, 1, sysdate(), null, null, '订单查询'),
(6211, '订单新增', 6202, 2, '#', '', '', 1, 0, 'F', '0', '0', 'yy:order:add', '#', 103, 1, sysdate(), null, null, '订单新增'),
(6212, '订单修改', 6202, 3, '#', '', '', 1, 0, 'F', '0', '0', 'yy:order:edit', '#', 103, 1, sysdate(), null, null, '订单修改'),
(6213, '订单删除', 6202, 4, '#', '', '', 1, 0, 'F', '0', '0', 'yy:order:remove', '#', 103, 1, sysdate(), null, null, '订单删除'),
(6214, '订单导出', 6202, 5, '#', '', '', 1, 0, 'F', '0', '0', 'yy:order:export', '#', 103, 1, sysdate(), null, null, '订单导出'),
(6299, '首页导出', 6201, 1, '#', '', '', 1, 0, 'F', '0', '0', 'yy:dashboard:export', '#', 103, 1, sysdate(), null, null, '首页汇总导出'),
(6215, '门店查询', 6203, 1, '#', '', '', 1, 0, 'F', '0', '0', 'yy:store:list', '#', 103, 1, sysdate(), null, null, '门店查询'),
(6216, '门店新增', 6203, 2, '#', '', '', 1, 0, 'F', '0', '0', 'yy:store:add', '#', 103, 1, sysdate(), null, null, '门店新增'),
(6217, '门店修改', 6203, 3, '#', '', '', 1, 0, 'F', '0', '0', 'yy:store:edit', '#', 103, 1, sysdate(), null, null, '门店修改'),
(6218, '门店删除', 6203, 4, '#', '', '', 1, 0, 'F', '0', '0', 'yy:store:remove', '#', 103, 1, sysdate(), null, null, '门店删除'),
(6219, '门店导出', 6203, 5, '#', '', '', 1, 0, 'F', '0', '0', 'yy:store:export', '#', 103, 1, sysdate(), null, null, '门店导出'),
(6220, '产品查询', 6204, 1, '#', '', '', 1, 0, 'F', '0', '0', 'yy:product:list', '#', 103, 1, sysdate(), null, null, '产品查询'),
(6221, '产品新增', 6204, 2, '#', '', '', 1, 0, 'F', '0', '0', 'yy:product:add', '#', 103, 1, sysdate(), null, null, '产品新增'),
(6222, '产品修改', 6204, 3, '#', '', '', 1, 0, 'F', '0', '0', 'yy:product:edit', '#', 103, 1, sysdate(), null, null, '产品修改'),
(6223, '产品删除', 6204, 4, '#', '', '', 1, 0, 'F', '0', '0', 'yy:product:remove', '#', 103, 1, sysdate(), null, null, '产品删除'),
(6224, '产品导出', 6204, 5, '#', '', '', 1, 0, 'F', '0', '0', 'yy:product:export', '#', 103, 1, sysdate(), null, null, '产品导出'),
(6225, '相册查询', 6205, 1, '#', '', '', 1, 0, 'F', '0', '0', 'yy:photoAlbum:list', '#', 103, 1, sysdate(), null, null, '相册查询'),
(6226, '相册新增', 6205, 2, '#', '', '', 1, 0, 'F', '0', '0', 'yy:photoAlbum:add', '#', 103, 1, sysdate(), null, null, '相册新增'),
(6227, '相册修改', 6205, 3, '#', '', '', 1, 0, 'F', '0', '0', 'yy:photoAlbum:edit', '#', 103, 1, sysdate(), null, null, '相册修改'),
(6228, '相册删除', 6205, 4, '#', '', '', 1, 0, 'F', '0', '0', 'yy:photoAlbum:remove', '#', 103, 1, sysdate(), null, null, '相册删除'),
(6229, '相册导出', 6205, 5, '#', '', '', 1, 0, 'F', '0', '0', 'yy:photoAlbum:export', '#', 103, 1, sysdate(), null, null, '相册导出'),
(6230, '底片查询', 6205, 6, '#', '', '', 1, 0, 'F', '0', '0', 'yy:photoAsset:list', '#', 103, 1, sysdate(), null, null, '底片查询'),
(6231, '底片新增', 6205, 7, '#', '', '', 1, 0, 'F', '0', '0', 'yy:photoAsset:add', '#', 103, 1, sysdate(), null, null, '底片新增'),
(6232, '底片修改', 6205, 8, '#', '', '', 1, 0, 'F', '0', '0', 'yy:photoAsset:edit', '#', 103, 1, sysdate(), null, null, '底片修改'),
(6233, '底片删除', 6205, 9, '#', '', '', 1, 0, 'F', '0', '0', 'yy:photoAsset:remove', '#', 103, 1, sysdate(), null, null, '底片删除'),
(6234, '底片导出', 6205, 10, '#', '', '', 1, 0, 'F', '0', '0', 'yy:photoAsset:export', '#', 103, 1, sysdate(), null, null, '底片导出'),
(6235, '插件查询', 6206, 1, '#', '', '', 1, 0, 'F', '0', '0', 'yy:channelPlugin:list', '#', 103, 1, sysdate(), null, null, '插件查询'),
(6236, '插件新增', 6206, 2, '#', '', '', 1, 0, 'F', '0', '0', 'yy:channelPlugin:add', '#', 103, 1, sysdate(), null, null, '插件新增'),
(6237, '插件修改', 6206, 3, '#', '', '', 1, 0, 'F', '0', '0', 'yy:channelPlugin:edit', '#', 103, 1, sysdate(), null, null, '插件修改'),
(6238, '插件删除', 6206, 4, '#', '', '', 1, 0, 'F', '0', '0', 'yy:channelPlugin:remove', '#', 103, 1, sysdate(), null, null, '插件删除'),
(6239, '插件导出', 6206, 5, '#', '', '', 1, 0, 'F', '0', '0', 'yy:channelPlugin:export', '#', 103, 1, sysdate(), null, null, '插件导出'),
(6240, '账号查询', 6206, 6, '#', '', '', 1, 0, 'F', '0', '0', 'yy:channelAccount:list', '#', 103, 1, sysdate(), null, null, '账号查询'),
(6241, '账号新增', 6206, 7, '#', '', '', 1, 0, 'F', '0', '0', 'yy:channelAccount:add', '#', 103, 1, sysdate(), null, null, '账号新增'),
(6242, '账号修改', 6206, 8, '#', '', '', 1, 0, 'F', '0', '0', 'yy:channelAccount:edit', '#', 103, 1, sysdate(), null, null, '账号修改'),
(6243, '账号删除', 6206, 9, '#', '', '', 1, 0, 'F', '0', '0', 'yy:channelAccount:remove', '#', 103, 1, sysdate(), null, null, '账号删除'),
(6244, '微信生态查询', 6209, 1, '#', '', '', 1, 0, 'F', '0', '0', 'yy:wechat:list', '#', 103, 1, sysdate(), null, null, '微信生态查询'),
(6245, '微信通知发送', 6209, 2, '#', '', '', 1, 0, 'F', '0', '0', 'yy:wechat:send', '#', 103, 1, sysdate(), null, null, '微信通知测试发送'),
(6257, '企业结构查询', 6250, 1, '#', '', '', 1, 0, 'F', '0', '0', 'yy:enterprise:list', '#', 103, 1, sysdate(), null, null, '企业结构查询'),
(6258, '预约配置查询', 6251, 1, '#', '', '', 1, 0, 'F', '0', '0', 'yy:bookingConfig:list', '#', 103, 1, sysdate(), null, null, '预约配置查询'),
(6259, '员工查询', 6252, 1, '#', '', '', 1, 0, 'F', '0', '0', 'yy:employee:list', '#', 103, 1, sysdate(), null, null, '员工查询'),
(6270, '预约配置详情', 6251, 2, '#', '', '', 1, 0, 'F', '0', '0', 'yy:bookingConfig:query', '#', 103, 1, sysdate(), null, null, '预约配置详情'),
(6271, '预约配置新增', 6251, 3, '#', '', '', 1, 0, 'F', '0', '0', 'yy:bookingConfig:add', '#', 103, 1, sysdate(), null, null, '预约配置新增'),
(6272, '预约配置修改', 6251, 4, '#', '', '', 1, 0, 'F', '0', '0', 'yy:bookingConfig:edit', '#', 103, 1, sysdate(), null, null, '预约配置修改'),
(6273, '预约配置删除', 6251, 5, '#', '', '', 1, 0, 'F', '0', '0', 'yy:bookingConfig:remove', '#', 103, 1, sysdate(), null, null, '预约配置删除'),
(6274, '预约配置导出', 6251, 6, '#', '', '', 1, 0, 'F', '0', '0', 'yy:bookingConfig:export', '#', 103, 1, sysdate(), null, null, '预约配置导出'),
(6275, '员工详情', 6252, 2, '#', '', '', 1, 0, 'F', '0', '0', 'yy:employee:query', '#', 103, 1, sysdate(), null, null, '员工详情'),
(6276, '员工新增', 6252, 3, '#', '', '', 1, 0, 'F', '0', '0', 'yy:employee:add', '#', 103, 1, sysdate(), null, null, '员工新增'),
(6277, '员工修改', 6252, 4, '#', '', '', 1, 0, 'F', '0', '0', 'yy:employee:edit', '#', 103, 1, sysdate(), null, null, '员工修改'),
(6278, '员工删除', 6252, 5, '#', '', '', 1, 0, 'F', '0', '0', 'yy:employee:remove', '#', 103, 1, sysdate(), null, null, '员工删除'),
(6279, '员工导出', 6252, 6, '#', '', '', 1, 0, 'F', '0', '0', 'yy:employee:export', '#', 103, 1, sysdate(), null, null, '员工导出'),
(6264, '客户查询', 6253, 1, '#', '', '', 1, 0, 'F', '0', '0', 'yy:customer:list', '#', 103, 1, sysdate(), null, null, '客户查询'),
(6265, '客户详情', 6253, 2, '#', '', '', 1, 0, 'F', '0', '0', 'yy:customer:query', '#', 103, 1, sysdate(), null, null, '客户详情'),
(6266, '客户新增', 6253, 3, '#', '', '', 1, 0, 'F', '0', '0', 'yy:customer:add', '#', 103, 1, sysdate(), null, null, '客户新增'),
(6267, '客户修改', 6253, 4, '#', '', '', 1, 0, 'F', '0', '0', 'yy:customer:edit', '#', 103, 1, sysdate(), null, null, '客户修改'),
(6268, '客户删除', 6253, 5, '#', '', '', 1, 0, 'F', '0', '0', 'yy:customer:remove', '#', 103, 1, sysdate(), null, null, '客户删除'),
(6269, '客户导出', 6253, 6, '#', '', '', 1, 0, 'F', '0', '0', 'yy:customer:export', '#', 103, 1, sysdate(), null, null, '客户导出'),
(6261, '通知查询', 6254, 1, '#', '', '', 1, 0, 'F', '0', '0', 'yy:notification:list', '#', 103, 1, sysdate(), null, null, '通知查询'),
(6280, '通知详情', 6254, 2, '#', '', '', 1, 0, 'F', '0', '0', 'yy:notification:query', '#', 103, 1, sysdate(), null, null, '通知详情'),
(6281, '通知新增', 6254, 3, '#', '', '', 1, 0, 'F', '0', '0', 'yy:notification:add', '#', 103, 1, sysdate(), null, null, '通知新增'),
(6282, '通知修改', 6254, 4, '#', '', '', 1, 0, 'F', '0', '0', 'yy:notification:edit', '#', 103, 1, sysdate(), null, null, '通知修改'),
(6283, '通知删除', 6254, 5, '#', '', '', 1, 0, 'F', '0', '0', 'yy:notification:remove', '#', 103, 1, sysdate(), null, null, '通知删除'),
(6284, '通知导出', 6254, 6, '#', '', '', 1, 0, 'F', '0', '0', 'yy:notification:export', '#', 103, 1, sysdate(), null, null, '通知导出'),
(6262, '报表查询', 6255, 1, '#', '', '', 1, 0, 'F', '0', '0', 'yy:report:list', '#', 103, 1, sysdate(), null, null, '报表查询'),
(6285, '报表详情', 6255, 2, '#', '', '', 1, 0, 'F', '0', '0', 'yy:report:query', '#', 103, 1, sysdate(), null, null, '报表详情'),
(6286, '报表新增', 6255, 3, '#', '', '', 1, 0, 'F', '0', '0', 'yy:report:add', '#', 103, 1, sysdate(), null, null, '报表新增'),
(6287, '报表修改', 6255, 4, '#', '', '', 1, 0, 'F', '0', '0', 'yy:report:edit', '#', 103, 1, sysdate(), null, null, '报表修改'),
(6288, '报表删除', 6255, 5, '#', '', '', 1, 0, 'F', '0', '0', 'yy:report:remove', '#', 103, 1, sysdate(), null, null, '报表删除'),
(6289, '报表导出', 6255, 6, '#', '', '', 1, 0, 'F', '0', '0', 'yy:report:export', '#', 103, 1, sysdate(), null, null, '报表导出'),
(6263, '多端配置查询', 6256, 1, '#', '', '', 1, 0, 'F', '0', '0', 'yy:mobile:list', '#', 103, 1, sysdate(), null, null, '多端配置查询'),
(6290, '多端配置详情', 6256, 2, '#', '', '', 1, 0, 'F', '0', '0', 'yy:mobile:query', '#', 103, 1, sysdate(), null, null, '多端配置详情'),
(6291, '多端配置新增', 6256, 3, '#', '', '', 1, 0, 'F', '0', '0', 'yy:mobile:add', '#', 103, 1, sysdate(), null, null, '多端配置新增'),
(6292, '多端配置修改', 6256, 4, '#', '', '', 1, 0, 'F', '0', '0', 'yy:mobile:edit', '#', 103, 1, sysdate(), null, null, '多端配置修改'),
(6293, '多端配置删除', 6256, 5, '#', '', '', 1, 0, 'F', '0', '0', 'yy:mobile:remove', '#', 103, 1, sysdate(), null, null, '多端配置删除'),
(6294, '多端配置导出', 6256, 6, '#', '', '', 1, 0, 'F', '0', '0', 'yy:mobile:export', '#', 103, 1, sysdate(), null, null, '多端配置导出');
