-- 服务生产模块结构迁移
-- 目标：
-- 1. 三方修图中心从 yy_photo_album / yy_photo_asset 自动派生修图任务，但使用独立任务表承接派单、阻塞和验收状态。
-- 2. 三方修图服务商、中央修图策略、开通许可证不占用历史备注字段，统一落到专表。

create table if not exists yy_retouch_provider (
    id                  bigint(20)   not null                    comment '主键',
    tenant_id           varchar(20)  default '000000'            comment '租户编号',
    provider_code       varchar(64)  not null                    comment '服务商编码',
    provider_name       varchar(128) not null                    comment '服务商名称',
    contact_name        varchar(64)  default ''                  comment '联系人',
    contact_phone       varchar(32)  default ''                  comment '联系电话',
    supported_store_ids varchar(500) default ''                  comment '适用门店ID列表，逗号分隔；空串表示全门店',
    service_scope       varchar(255) default ''                  comment '服务范围',
    quote_mode          varchar(32)  default 'PER_PHOTO'         comment '报价模式',
    settlement_mode     varchar(32)  default 'MONTHLY'           comment '结算模式',
    application_status  varchar(32)  default 'PENDING'           comment '入驻审核状态',
    status              varchar(32)  default 'ACTIVE'            comment '服务状态',
    rating_score        int          default 5                   comment '评分',
    sla_hours           int          default 24                  comment 'SLA小时数',
    create_dept         bigint(20)   default null                comment '创建部门',
    create_by           bigint(20)   default null                comment '创建者',
    create_time         datetime                                comment '创建时间',
    update_by           bigint(20)   default null                comment '更新者',
    update_time         datetime                                comment '更新时间',
    del_flag            char(1)      default '0'                 comment '删除标志',
    remark              varchar(500) default null                comment '备注',
    primary key (id),
    unique key uk_yy_retouch_provider_code (tenant_id, provider_code),
    key idx_yy_retouch_provider_status (tenant_id, status, application_status)
) engine=innodb comment='三方修图服务商';

create table if not exists yy_retouch_task (
    id                 bigint(20)   not null                    comment '主键',
    tenant_id          varchar(20)  default '000000'            comment '租户编号',
    store_id           bigint(20)   not null                    comment '门店ID',
    order_id           bigint(20)   default null                comment '订单ID',
    album_id           bigint(20)   default null                comment '相册ID',
    provider_id        bigint(20)   default null                comment '服务商ID',
    provider_name      varchar(128) default ''                  comment '服务商名称快照',
    task_no            varchar(64)  not null                    comment '修图任务编号',
    status             varchar(32)  default 'WAIT_ASSIGN'       comment '任务状态',
    acceptance_status  varchar(32)  default 'PENDING'           comment '验收状态',
    quote_amount_cent  bigint(20)   default 0                   comment '报价金额（分）',
    due_time           datetime                                comment '截止时间',
    submitted_time     datetime                                comment '提交时间',
    completed_time     datetime                                comment '完成时间',
    source_stage       varchar(32)  default 'CONFIRMED'         comment '来源阶段',
    customer_name      varchar(64)  default ''                  comment '客户姓名',
    service_name       varchar(128) default ''                  comment '服务名称快照',
    block_reason       varchar(255) default ''                  comment '阻塞原因',
    create_dept        bigint(20)   default null                comment '创建部门',
    create_by          bigint(20)   default null                comment '创建者',
    create_time        datetime                                comment '创建时间',
    update_by          bigint(20)   default null                comment '更新者',
    update_time        datetime                                comment '更新时间',
    del_flag           char(1)      default '0'                 comment '删除标志',
    remark             varchar(500) default null                comment '备注',
    primary key (id),
    unique key uk_yy_retouch_task_no (tenant_id, task_no),
    key idx_yy_retouch_task_store (tenant_id, store_id, status, due_time),
    key idx_yy_retouch_task_album (tenant_id, album_id)
) engine=innodb comment='三方修图任务';

create table if not exists yy_collaboration_policy (
    id                    bigint(20)    not null                    comment '主键',
    tenant_id             varchar(20)   default '000000'            comment '租户编号',
    policy_code           varchar(64)   not null                    comment '策略编码',
    review_flow_enabled   char(1)       default '1'                 comment '是否启用审片流程',
    product_info_mask_mode varchar(32)  default 'MASK_PHOTO_ONLY'   comment '产品信息隐藏策略',
    enabled_store_ids     varchar(500)  default ''                  comment '启用门店ID列表，逗号分隔；空串表示全门店',
    fallback_action       varchar(32)   default 'RETURN_TO_STORE'   comment '异常退回动作',
    transfer_enabled      char(1)       default '1'                 comment '是否允许转派',
    auto_dispatch_mode    varchar(32)   default 'STORE_ONLY'        comment '自动派单模式',
    gender_makeup_enabled char(1)       default '0'                 comment '是否区分男女妆面',
    female_makeup_ratio   decimal(10,2) default 1.50                comment '女妆业绩系数',
    create_dept           bigint(20)    default null                comment '创建部门',
    create_by             bigint(20)    default null                comment '创建者',
    create_time           datetime                                 comment '创建时间',
    update_by             bigint(20)    default null                comment '更新者',
    update_time           datetime                                 comment '更新时间',
    del_flag              char(1)       default '0'                 comment '删除标志',
    remark                varchar(500)  default null                comment '备注',
    primary key (id),
    unique key uk_yy_collaboration_policy_code (tenant_id, policy_code)
) engine=innodb comment='内部协作策略';

create table if not exists yy_service_license_binding (
    id               bigint(20)   not null                    comment '主键',
    tenant_id        varchar(20)  default '000000'            comment '租户编号',
    license_key      varchar(128) not null                    comment '许可证Key',
    plan_name        varchar(128) default ''                  comment '套餐名称',
    status           varchar(32)  default 'ACTIVE'            comment '许可证状态',
    expire_time      datetime                                comment '过期时间',
    bound_store_ids  varchar(500) default ''                  comment '绑定门店ID列表，逗号分隔',
    seat_count       int          default 1                   comment '席位数',
    activated_time   datetime                                comment '激活时间',
    renew_action     varchar(32)  default 'RENEW'             comment '续期动作',
    create_dept      bigint(20)   default null                comment '创建部门',
    create_by        bigint(20)   default null                comment '创建者',
    create_time      datetime                                comment '创建时间',
    update_by        bigint(20)   default null                comment '更新者',
    update_time      datetime                                comment '更新时间',
    del_flag         char(1)      default '0'                 comment '删除标志',
    remark           varchar(500) default null                comment '备注',
    primary key (id),
    unique key uk_yy_service_license_key (tenant_id, license_key),
    key idx_yy_service_license_status (tenant_id, status, expire_time)
) engine=innodb comment='协作套件许可证';
