import type { OrderStatusStatDto, ScheduleItemDto, TodaySlotDto, TrendStatDto } from '../api/backend'
import { formatDate } from './appStoreTransforms'
import type { BookingInventorySlot, BookingOrder, StoreInfo, StudioInfo } from './appStoreTypes'

export const createDemoStores = (): StoreInfo[] => [
  {
    backendId: '1',
    id: 'YY-SZ-001',
    name: '影约云深圳旗舰店',
    status: '营业中',
    manager: '主管 · 门店账号',
    monthlyOrders: '128',
    pendingOrders: '9',
    address: '深圳市南山区科技园影像中心 3F',
    phone: '0755-8888 2026',
    hours: '09:30 - 21:00',
  },
  {
    backendId: '2',
    id: 'YY-HK-001',
    name: '影约云香港交付点',
    status: '预约制',
    manager: '主管 · 交付团队',
    monthlyOrders: '42',
    pendingOrders: '3',
    address: '香港九龙尖沙咀摄影服务点',
    phone: '+852 6000 2026',
    hours: '10:00 - 20:00',
  },
]

export const createDemoOrders = (today: string, tomorrow: string): BookingOrder[] => [
  {
    backendId: '9001',
    storeBackendId: '1',
    productBackendId: '101',
    id: 'YY202606100001',
    customer: '陈女士',
    phone: '13800003333',
    store: '影约云深圳旗舰店',
    service: '证件照精修套餐',
    source: '抖音来客',
    method: '到店拍摄',
    orderTime: `${today.slice(5)} 09:20`,
    orderDate: today,
    orderClock: '09:20',
    arrivalTime: `${today.slice(5)} 14:00`,
    status: '选片中',
    payment: '已支付',
    amount: 129,
    arrivalDate: today,
    arrivalClock: '14:00',
  },
  {
    backendId: '9002',
    storeBackendId: '1',
    productBackendId: '102',
    id: 'YY202606100002',
    customer: '林先生',
    phone: '13900004444',
    store: '影约云深圳旗舰店',
    service: '个人形象照套餐',
    source: '微信预约',
    method: '到店拍摄',
    orderTime: `${today.slice(5)} 10:40`,
    orderDate: today,
    orderClock: '10:40',
    arrivalTime: `${tomorrow.slice(5)} 11:30`,
    status: '已确认',
    payment: '已支付',
    amount: 399,
    arrivalDate: tomorrow,
    arrivalClock: '11:30',
  },
  {
    backendId: '9003',
    storeBackendId: '2',
    productBackendId: '101',
    id: 'YY202606100003',
    customer: '周同学',
    phone: '13700005555',
    store: '影约云香港交付点',
    service: '证件照精修套餐',
    source: '手工录入',
    method: '线上取片',
    orderTime: `${today.slice(5)} 11:15`,
    orderDate: today,
    orderClock: '11:15',
    arrivalTime: `${today.slice(5)} 16:30`,
    status: '待确认',
    payment: '待支付',
    amount: 129,
    arrivalDate: today,
    arrivalClock: '16:30',
  },
]

export const createDemoStudios = (): StudioInfo[] => [
  { backendId: '1', storeBackendId: '1', id: '1', name: 'A 棚 · 证件照', status: '可预约' },
  { backendId: '2', storeBackendId: '1', id: '2', name: 'B 棚 · 形象照', status: '可预约' },
  { backendId: '3', storeBackendId: '2', id: '3', name: 'HK 交付工位', status: '预约制' },
]

export const createDemoBookingInventory = (today: string): BookingInventorySlot[] => [
  {
    backendId: '2101',
    storeBackendId: '1',
    storeName: '影约云深圳旗舰店',
    serviceGroupBackendId: '1101',
    serviceGroupName: '证件照快拍组',
    date: today,
    startTime: '14:00',
    endTime: '14:30',
    capacity: 6,
    confirmedCount: 4,
    conflictCount: 0,
    status: 'ACTIVE',
    remark: '正常承接',
    externalSkuId: '',
  },
  {
    backendId: '2102',
    storeBackendId: '1',
    storeName: '影约云深圳旗舰店',
    serviceGroupBackendId: '1102',
    serviceGroupName: '形象照主棚',
    date: today,
    startTime: '15:00',
    endTime: '16:30',
    capacity: 3,
    confirmedCount: 3,
    conflictCount: 1,
    status: 'ACTIVE',
    remark: '抖音与微信同一时段重叠，需要人工改期',
    externalSkuId: '',
  },
  {
    backendId: '2103',
    storeBackendId: '2',
    storeName: '影约云香港交付点',
    serviceGroupBackendId: '1103',
    serviceGroupName: '交付与取片组',
    date: today,
    startTime: '16:30',
    endTime: '17:00',
    capacity: 2,
    confirmedCount: 1,
    conflictCount: 0,
    status: 'ACTIVE',
    remark: '可继续安排交付',
    externalSkuId: '',
  },
]

export const createDemoScheduleItems = (today: string): ScheduleItemDto[] => [
  {
    bookingId: '6001',
    orderId: '9001',
    storeId: '1',
    studioId: '1',
    studioName: 'A 棚 · 证件照',
    startAt: `${today}T14:00:00`,
    endAt: `${today}T14:40:00`,
    bookingStatus: '已确认',
    orderNo: 'YY202606100001',
    customerName: '陈女士',
    customerPhone: '13800003333',
    serviceName: '证件照精修套餐',
    orderStatus: '选片中',
  },
  {
    bookingId: '6002',
    orderId: '9003',
    storeId: '2',
    studioId: '3',
    studioName: 'HK 交付工位',
    startAt: `${today}T16:30:00`,
    endAt: `${today}T17:00:00`,
    bookingStatus: '待确认',
    orderNo: 'YY202606100003',
    customerName: '周同学',
    customerPhone: '13700005555',
    serviceName: '证件照精修套餐',
    orderStatus: '待确认',
  },
]

export const createDemoOrderStatusStats = (): OrderStatusStatDto[] => [
  { status: '待服务', label: '待服务', count: 1, amountCents: 12900 },
  { status: '服务中', label: '服务中', count: 1, amountCents: 39900 },
  { status: '已完成', label: '已完成', count: 1, amountCents: 12900 },
  { status: '已取消', label: '已取消', count: 0, amountCents: 0 },
  { status: '已退单', label: '已退单', count: 0, amountCents: 0 },
]

export const createDemoTrendStats = (): TrendStatDto[] =>
  Array.from({ length: 20 }, (_, idx) => {
    const day = formatDate(new Date(Date.now() - (19 - idx) * 24 * 60 * 60 * 1000))
    return {
      day,
      bookedCount: 4 + ((idx * 3) % 7),
      arrivedCount: 2 + ((idx * 2) % 5),
      amountCents: (600 + idx * 38) * 100,
    }
  })

export const createDemoTodaySlots = (scheduleItems: ScheduleItemDto[], stores: StoreInfo[]): TodaySlotDto[] =>
  scheduleItems.map(item => ({
    bookingId: item.bookingId,
    storeId: item.storeId,
    storeName: stores.find(store => store.backendId === item.storeId)?.name ?? '影约云门店',
    studioId: item.studioId,
    studioName: item.studioName,
    startAt: item.startAt,
    endAt: item.endAt,
    bookingStatus: item.bookingStatus,
    orderId: item.orderId,
    orderNo: item.orderNo,
    customerName: item.customerName,
    orderStatus: item.orderStatus,
  }))
