import { normalizeBackendId, optionalBackendId } from './backendId'
import type {
  CollaborationPolicyDto,
  RetouchProviderDto,
  RetouchTaskDto,
  ServiceLicenseBindingDto,
} from './backendTypes'

export const mapRetouchTaskRow = (row: Record<string, any>): RetouchTaskDto => ({
  id: normalizeBackendId(row.id),
  tenantId: String(row.tenantId ?? ''),
  storeId: optionalBackendId(row.storeId) ?? null,
  storeName: String(row.storeName ?? ''),
  orderId: optionalBackendId(row.orderId) ?? null,
  orderNo: String(row.orderNo ?? ''),
  albumId: optionalBackendId(row.albumId) ?? null,
  albumName: String(row.albumName ?? ''),
  providerId: optionalBackendId(row.providerId) ?? null,
  providerName: String(row.providerName ?? ''),
  taskNo: String(row.taskNo ?? ''),
  status: String(row.status ?? 'WAIT_ASSIGN'),
  acceptanceStatus: String(row.acceptanceStatus ?? 'PENDING'),
  quoteAmountCent: Number(row.quoteAmountCent ?? 0),
  dueTime: String(row.dueTime ?? ''),
  submittedTime: String(row.submittedTime ?? ''),
  completedTime: String(row.completedTime ?? ''),
  sourceStage: String(row.sourceStage ?? ''),
  customerName: String(row.customerName ?? ''),
  serviceName: String(row.serviceName ?? ''),
  blockReason: String(row.blockReason ?? ''),
  remark: String(row.remark ?? ''),
  createTime: String(row.createTime ?? ''),
  updateTime: String(row.updateTime ?? ''),
})

export const mapRetouchProviderRow = (row: Record<string, any>): RetouchProviderDto => ({
  id: normalizeBackendId(row.id),
  tenantId: String(row.tenantId ?? ''),
  providerCode: String(row.providerCode ?? ''),
  providerName: String(row.providerName ?? ''),
  contactName: String(row.contactName ?? ''),
  contactPhone: String(row.contactPhone ?? ''),
  supportedStoreIds: String(row.supportedStoreIds ?? ''),
  serviceScope: String(row.serviceScope ?? ''),
  quoteMode: String(row.quoteMode ?? 'PER_PHOTO'),
  settlementMode: String(row.settlementMode ?? 'MONTHLY'),
  applicationStatus: String(row.applicationStatus ?? 'PENDING'),
  status: String(row.status ?? 'ACTIVE'),
  ratingScore: Number(row.ratingScore ?? 0),
  slaHours: Number(row.slaHours ?? 0),
  remark: String(row.remark ?? ''),
  createTime: String(row.createTime ?? ''),
  updateTime: String(row.updateTime ?? ''),
})

export const mapCollaborationPolicyRow = (row: Record<string, any>): CollaborationPolicyDto => ({
  id: optionalBackendId(row.id),
  tenantId: String(row.tenantId ?? ''),
  policyCode: String(row.policyCode ?? 'DEFAULT'),
  reviewFlowEnabled: String(row.reviewFlowEnabled ?? '1'),
  productInfoMaskMode: String(row.productInfoMaskMode ?? 'MASK_PHOTO_ONLY'),
  enabledStoreIds: String(row.enabledStoreIds ?? ''),
  fallbackAction: String(row.fallbackAction ?? 'RETURN_TO_STORE'),
  transferEnabled: String(row.transferEnabled ?? '1'),
  autoDispatchMode: String(row.autoDispatchMode ?? 'STORE_ONLY'),
  genderMakeupEnabled: String(row.genderMakeupEnabled ?? '0'),
  femaleMakeupRatio: Number(row.femaleMakeupRatio ?? 1.5),
  remark: String(row.remark ?? ''),
  createTime: String(row.createTime ?? ''),
  updateTime: String(row.updateTime ?? ''),
})

export const mapServiceLicenseBindingRow = (row: Record<string, any>): ServiceLicenseBindingDto => ({
  id: normalizeBackendId(row.id),
  tenantId: String(row.tenantId ?? ''),
  licenseKey: String(row.licenseKey ?? ''),
  planName: String(row.planName ?? ''),
  status: String(row.status ?? 'ACTIVE'),
  expireTime: String(row.expireTime ?? ''),
  boundStoreIds: String(row.boundStoreIds ?? ''),
  seatCount: Number(row.seatCount ?? 0),
  activatedTime: String(row.activatedTime ?? ''),
  renewAction: String(row.renewAction ?? 'RENEW'),
  remark: String(row.remark ?? ''),
  createTime: String(row.createTime ?? ''),
  updateTime: String(row.updateTime ?? ''),
})
