export interface YyOrderVO extends BaseEntity {
  id: string | number;
  storeId: string | number;
  orderNo: string;
  customerName: string;
  customerPhone: string;
  source: string;
  bookingMethod: string;
  orderTime: string;
  arrivalTime: string;
  status: string;
  workstationNo: string;
  externalOrderId: string;
  channelType?: string;
  totalAmountCent?: number;
  paidAmountCent?: number;
  payStatus?: string;
  paidTime?: string;
  refundStatus?: string;
  refundAmountCent?: number;
  externalProductId?: string;
  externalSkuId?: string;
  externalPoiId?: string;
  serviceGroupId?: string | number;
  inventorySlotId?: string | number;
  slotDate?: string;
  slotStartTime?: string;
  slotEndTime?: string;
  inventoryStatus?: string;
  conflictReason?: string;
  externalStatus?: string;
  syncStatus?: string;
  photoAlbumCount?: number;
  photoVisibleAssetCount?: number;
  photoMissingObjectKeyCount?: number;
  remark: string;
  tenantId?: string;
}

export interface YyOrderForm {
  id?: string | number | undefined;
  storeId: string | number;
  orderNo: string;
  customerName: string;
  customerPhone: string;
  source: string;
  bookingMethod: string;
  orderTime: string;
  arrivalTime: string;
  status: string;
  workstationNo: string;
  externalOrderId: string;
  channelType?: string;
  totalAmountCent?: number;
  paidAmountCent?: number;
  payStatus?: string;
  paidTime?: string;
  refundStatus?: string;
  refundAmountCent?: number;
  externalProductId?: string;
  externalSkuId?: string;
  externalPoiId?: string;
  serviceGroupId?: string | number;
  inventorySlotId?: string | number;
  slotDate?: string;
  slotStartTime?: string;
  slotEndTime?: string;
  inventoryStatus?: string;
  conflictReason?: string;
  remark: string;
}

export interface YyOrderQuery extends PageQuery {
  keyword?: string;
  storeId?: string | number;
  orderNo?: string;
  customerName?: string;
  customerPhone?: string;
  source?: string;
  bookingMethod?: string;
  beginOrderTime?: string;
  endOrderTime?: string;
  beginArrivalTime?: string;
  endArrivalTime?: string;
  status?: string;
  externalOrderId?: string;
  channelType?: string;
  payStatus?: string;
  externalProductId?: string;
  externalSkuId?: string;
  externalPoiId?: string;
  serviceGroupId?: string | number;
  inventorySlotId?: string | number;
  slotDate?: string;
  slotStartTime?: string;
  slotEndTime?: string;
  inventoryStatus?: string;
  externalStatus?: string;
  syncStatus?: string;
  photoDeliveryIssueOnly?: string;
}
