import { definePhaseModuleScaffold } from '../system/phaseModuleRegistry'

const collaborationBaseContracts = [
  'docs/contracts/full-product-closed-loop-contract.md',
  'studio-workbench/src/shared/api/backendCollaborationApi.ts',
]

const fulfillmentOwnerLayers = {
  presentation: [
    'studio-workbench/src/features/collaboration/WorkExecutionOverviewView.vue',
    'studio-workbench/src/features/collaboration/WorkOrdersView.vue',
    'studio-workbench/src/features/collaboration/WorkOrderExportView.vue',
    'studio-workbench/src/features/collaboration/WorkOrderStatisticsView.vue',
  ],
  control: ['studio-workbench/src/shared/api/backendCollaborationApi.ts'],
  data: ['yy_work_order', 'yy_work_order_event'],
}

const governanceOwnerLayers = {
  presentation: [
    'studio-workbench/src/features/collaboration/CollaborationPositionSettingsView.vue',
    'studio-workbench/src/features/collaboration/CollaborationProductSettingsView.vue',
    'studio-workbench/src/features/collaboration/CollaborationRetouchCenterSettingsView.vue',
    'studio-workbench/src/features/collaboration/CollaborationCommonSettingsView.vue',
    'studio-workbench/src/features/collaboration/CollaborationOpenSettingsView.vue',
  ],
  control: ['studio-workbench/src/shared/api/backendCollaborationApi.ts'],
  data: ['yy_collaboration_setting', 'yy_product_collaboration_config', 'yy_collaboration_license', 'yy_collaboration_license_store'],
}

export const collaborationScaffolds = [
  definePhaseModuleScaffold({
    featureKey: 'collaboration-overview',
    phase: 'Phase 2',
    ownerStatus: 'ready',
    domain: '内部协作',
    title: '工作执行概况',
    summary: '工单执行总览继续走真实工单主链 owner。',
    owner: 'studio-workbench/src/features/collaboration',
    nextPhase: 'Phase 2 继续补阻塞原因、超时趋势和门店绩效联动。',
    routes: ['/collaboration/overview'],
    contracts: collaborationBaseContracts,
    apis: ['backendApi.listWorkOrders()', 'backendApi.listWorkOrderEvents()'],
    ledgers: ['yy_work_order', 'yy_work_order_event'],
    ownerLayers: fulfillmentOwnerLayers,
  }),
  definePhaseModuleScaffold({
    featureKey: 'collaboration-work-orders',
    phase: 'Phase 2',
    ownerStatus: 'ready',
    domain: '内部协作',
    title: '工单管理',
    summary: '工单主链、状态流转和事件审计统一由工单 owner 管理。',
    owner: 'studio-workbench/src/features/collaboration',
    nextPhase: 'Phase 2 继续补重派、回退和高风险审批。',
    routes: ['/collaboration/work-orders'],
    contracts: collaborationBaseContracts,
    apis: ['backendApi.listWorkOrders()', 'backendApi.transitionWorkOrder()'],
    ledgers: ['yy_work_order', 'yy_work_order_event'],
    ownerLayers: fulfillmentOwnerLayers,
  }),
  definePhaseModuleScaffold({
    featureKey: 'collaboration-export',
    phase: 'Phase 2',
    ownerStatus: 'ready',
    domain: '内部协作',
    title: '工单数据导出',
    summary: '协作导出继续从真实工单主链导出，不在页面内拼 CSV 规则。',
    owner: 'studio-workbench/src/features/collaboration',
    nextPhase: 'Phase 2 继续补异步任务中心和导出审计记录。',
    routes: ['/collaboration/export'],
    contracts: collaborationBaseContracts,
    apis: ['backendApi.exportWorkOrders()'],
    ledgers: ['yy_work_order', 'yy_work_order_event'],
    ownerLayers: fulfillmentOwnerLayers,
  }),
  definePhaseModuleScaffold({
    featureKey: 'collaboration-statistics',
    phase: 'Phase 2',
    ownerStatus: 'ready',
    domain: '内部协作',
    title: '环节统计',
    summary: '岗位阻塞、超时和进度统计继续统一从工单事实派生。',
    owner: 'studio-workbench/src/features/collaboration',
    nextPhase: 'Phase 2 继续补平均耗时和岗位 SLA 趋势。',
    routes: ['/collaboration/statistics'],
    contracts: collaborationBaseContracts,
    apis: ['backendApi.listWorkOrderStatistics()'],
    ledgers: ['yy_work_order', 'yy_work_order_event'],
    ownerLayers: fulfillmentOwnerLayers,
  }),
  definePhaseModuleScaffold({
    featureKey: 'collaboration-positions',
    phase: 'Phase 4',
    ownerStatus: 'ready',
    domain: '内部协作',
    title: '岗位设置',
    summary: '岗位顺序、门店范围和默认 SLA 继续由协作设置 owner 管理。',
    owner: 'studio-workbench/src/features/collaboration',
    nextPhase: 'Phase 4 继续补审批流和岗位插件授权。',
    routes: ['/collaboration/positions'],
    contracts: collaborationBaseContracts,
    apis: ['collaborationApi.getSetting()', 'collaborationApi.saveSetting()'],
    ledgers: ['yy_collaboration_setting'],
    ownerLayers: governanceOwnerLayers,
  }),
  definePhaseModuleScaffold({
    featureKey: 'collaboration-product-settings',
    phase: 'Phase 4',
    ownerStatus: 'ready',
    domain: '内部协作',
    title: '产品设置',
    summary: '产品级协作流转、时限和节点开关统一由协作产品配置 owner 管理。',
    owner: 'studio-workbench/src/features/collaboration',
    nextPhase: 'Phase 4 继续补多品牌模板和插件化流程。',
    routes: ['/collaboration/product-settings'],
    contracts: collaborationBaseContracts,
    apis: ['collaborationApi.listProductConfigs()', 'collaborationApi.saveProductConfig()'],
    ledgers: ['yy_product_collaboration_config'],
    ownerLayers: governanceOwnerLayers,
  }),
  definePhaseModuleScaffold({
    featureKey: 'collaboration-retouch-center-settings',
    phase: 'Phase 4',
    ownerStatus: 'ready',
    domain: '内部协作',
    title: '中央修图设置',
    summary: '中央修图审片和转派规则继续统一归协作设置 owner。',
    owner: 'studio-workbench/src/features/collaboration',
    nextPhase: 'Phase 4 继续补跨品牌默认模板和许可证限制。',
    routes: ['/collaboration/retouch-center-settings'],
    contracts: collaborationBaseContracts,
    apis: ['collaborationApi.getSetting()', 'collaborationApi.saveSetting()'],
    ledgers: ['yy_collaboration_setting'],
    ownerLayers: governanceOwnerLayers,
  }),
  definePhaseModuleScaffold({
    featureKey: 'collaboration-common-settings',
    phase: 'Phase 4',
    ownerStatus: 'ready',
    domain: '内部协作',
    title: '通用设置',
    summary: '自动派单、自动完单和启用范围继续走统一协作设置 owner。',
    owner: 'studio-workbench/src/features/collaboration',
    nextPhase: 'Phase 4 继续补租户级治理和默认策略回放。',
    routes: ['/collaboration/common-settings'],
    contracts: collaborationBaseContracts,
    apis: ['collaborationApi.getSetting()', 'collaborationApi.saveSetting()'],
    ledgers: ['yy_collaboration_setting'],
    ownerLayers: governanceOwnerLayers,
  }),
  definePhaseModuleScaffold({
    featureKey: 'collaboration-open-settings',
    phase: 'Phase 4',
    ownerStatus: 'ready',
    domain: '内部协作',
    title: '开通设置',
    summary: '许可证、门店绑定和授权范围继续统一收口到开通设置 owner。',
    owner: 'studio-workbench/src/features/collaboration',
    nextPhase: 'Phase 4 继续补套餐插件、审批和多租户资源隔离。',
    routes: ['/collaboration/open-settings'],
    contracts: collaborationBaseContracts,
    apis: [
      'collaborationApi.listLicenses()',
      'collaborationApi.saveLicense()',
      'collaborationApi.bindLicenseStore()',
      'collaborationApi.unbindLicenseStore()',
    ],
    ledgers: ['yy_collaboration_license', 'yy_collaboration_license_store'],
    ownerLayers: governanceOwnerLayers,
  }),
]
