import fs from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'vitest'

const repoRoot = path.resolve(process.cwd(), '..')
const readRepoFile = (relativePath: string) =>
  fs.readFileSync(path.join(repoRoot, relativePath), 'utf8')

describe('studio workbench smoke script contracts', () => {
  const microFormSmoke = readRepoFile('tools/studio-workbench-micro-form-booking-smoke.mjs')
  const microFormRunner = readRepoFile('tools/run-studio-workbench-micro-form-booking-smoke.ps1')
  const realClickSmoke = readRepoFile('tools/studio-workbench-real-click-smoke.mjs')
  const realLoginSmoke = readRepoFile('tools/studio-workbench-real-login-smoke.mjs')
  const eventInboxReport = readRepoFile('tools/get-douyin-life-event-inbox-report.ps1')

  it('keeps micro-form full booking writes behind an explicit reversible gate', () => {
    expect(microFormSmoke).toContain('STUDIO_MF_CREATE_BOOKING')
    expect(microFormSmoke).toContain('createBooking')
    expect(microFormSmoke).toContain("'/yy/order/staff-booking'")
    expect(microFormSmoke).toContain('waitForSubmissionFollowed')
    expect(microFormSmoke).toContain('`/yy/microFormSubmission/${createdSubmissionId}`')
    expect(microFormSmoke).toContain("targetStatus: 'CANCELLED'")
    expect(microFormSmoke).toContain('paidCount')
    expect(microFormSmoke).toContain('followStatus')
    expect(microFormSmoke).toContain('orderId')
    expect(microFormSmoke).toContain('发送通知')
    expect(microFormSmoke).toContain('collectOperationLogEvidence')
    expect(microFormSmoke).toContain("'/monitor/operlog/list'")
    expect(microFormSmoke).toContain('Micro-form submission was not marked FOLLOWED with orderId')

    expect(microFormRunner).toContain('[switch]$CreateBooking')
    expect(microFormRunner).toContain('STUDIO_MF_CREATE_BOOKING')
  })

  it('keeps the Douyin Life event inbox report read-only and redacted', () => {
    expect(eventInboxReport).toContain('yy_channel_event_inbox')
    expect(eventInboxReport).toContain("'readOnly', true")
    expect(eventInboxReport).toContain('failureBuckets')
    expect(eventInboxReport).toContain('staleFailures')

    expect(eventInboxReport).not.toContain('raw_payload')
    expect(eventInboxReport).not.toContain('/event-inbox/{id}/retry')
    expect(eventInboxReport).not.toContain('orders/sync')
    expect(eventInboxReport).not.toContain('goodlife/v1')
  })

  it('covers real UI reschedule before cancellation in the reversible click smoke', () => {
    expect(realClickSmoke).toContain('chooseSlots')
    expect(realClickSmoke).toContain('/reschedule')
    expect(realClickSmoke).toContain('ui-reschedule')
    expect(realClickSmoke).toContain('inventory-reschedule')
    expect(realClickSmoke).toContain('afterRescheduleOld')
    expect(realClickSmoke).toContain('afterRescheduleNew')
    expect(realClickSmoke).toContain('new slot paidCount did not increase by 1')
    expect(realClickSmoke).toContain('old slot paidCount did not return after UI reschedule')
  })

  it('verifies visible operation evidence after real UI reschedule and cancellation', () => {
    expect(realClickSmoke).toContain('assertOperationEvidence')
    expect(realClickSmoke).toContain('assertOperationTimeline')
    expect(realClickSmoke).toContain("filter({ hasText: '订单操作总览' })")
    expect(realClickSmoke).not.toContain("page.locator('aside').first()")
    expect(realClickSmoke).toContain('operation-evidence-reschedule')
    expect(realClickSmoke).toContain('operation-evidence-status-')
    expect(realClickSmoke).toContain('operation-evidence-cancel')
    expect(realClickSmoke).toContain('operation-evidence-photo-notify')
    expect(realClickSmoke).toContain('operation-evidence-photo-confirm')
    expect(realClickSmoke).toContain('operation-evidence-photo-deliver')
    expect(realClickSmoke).toContain('operation-timeline-reschedule')
    expect(realClickSmoke).toContain('operation-timeline-status-')
    expect(realClickSmoke).toContain('operation-timeline-cancel')
    expect(realClickSmoke).toContain('operation-timeline-photo-notify')
    expect(realClickSmoke).toContain('operation-timeline-photo-confirm')
    expect(realClickSmoke).toContain('operation-timeline-photo-deliver')
    expect(realClickSmoke).toContain('最近操作证据')
    expect(realClickSmoke).toContain('完整操作记录')
    expect(realClickSmoke).toContain('operationStatusSuccessParts')
    expect(realClickSmoke).toContain('...operationStatusSuccessParts')
    expect(realClickSmoke).toContain('operationSourceParts')
    expect(realClickSmoke).toContain('...operationSourceParts')
    expect(realClickSmoke).toContain('状态流转')
    expect(realClickSmoke).toContain('目标时段')
    expect(realClickSmoke).toContain('目标状态')
    expect(realClickSmoke).toContain('原因')
    expect(realClickSmoke).toContain('操作人：')
    expect(realClickSmoke).toContain('门店/部门：')
    expect(realClickSmoke).toContain('操作来源：')
    expect(realClickSmoke).toContain('刷新最近操作证据')
    expect(realClickSmoke).toContain('刷新完整操作记录')
    expect(realClickSmoke).not.toContain("name: /^刷新$/")
    expect(realClickSmoke).toContain('客户要求改期')
    expect(realClickSmoke).toContain('客户主动取消')
  })

  it('covers photo delivery actions from the appointment order drawer', () => {
    expect(realClickSmoke).toContain('createLinkedSyntheticAlbum')
    expect(realClickSmoke).toContain('uploadAlbumFixtures')
    expect(realClickSmoke).toContain('submitAlbumSelectionAsClient')
    expect(realClickSmoke).toContain("'/yy/photoAlbum'")
    expect(realClickSmoke).toContain("'/yy/photoAsset'")
    expect(realClickSmoke).toContain('/client/photo/auth/verify')
    expect(realClickSmoke).toContain('/client/photo/albums/${album.id}/selection')
    expect(realClickSmoke).toContain('performOrderAlbumAction')
    expect(realClickSmoke).toContain('assertAlbumAfterDelivery')
    expect(realClickSmoke).toContain('getAlbumById')
    expect(realClickSmoke).toContain('summarizeAlbumById')
    expect(realClickSmoke).toContain('`/yy/photoAlbum/${albumId}`')
    expect(realClickSmoke).toContain('waitForEnabledAlbumActionButton')
    expect(realClickSmoke).toContain('waitForAlbumActionText')
    expect(realClickSmoke).toContain('album-delivered-backend')
    expect(realClickSmoke).toContain('selectionStatus')
    expect(realClickSmoke).toContain('button did not become enabled')
    expect(realClickSmoke).toContain('UI feedback missing expected parts')
    expect(realClickSmoke).toContain('订单详情通知客户')
    expect(realClickSmoke).toContain('订单详情确认客片')
    expect(realClickSmoke).toContain('订单详情发送资料')
    expect(realClickSmoke).toContain('相册：')
    expect(realClickSmoke).toContain('ui-photo-notify')
    expect(realClickSmoke).toContain('ui-photo-confirm')
    expect(realClickSmoke).toContain('ui-photo-deliver')
    expect(realClickSmoke).toContain('客片交付状态')
    expect(realClickSmoke).toContain('已交付')
    expect(realClickSmoke).toContain("newSlotOrdersUrl.searchParams.set('slotOriginDate', newSlot.bizDate)")
  })

  it('keeps only known browser resource-close console noise non-fatal', () => {
    expect(realClickSmoke).toContain('ignoredConsoleErrors')
    expect(realClickSmoke).toContain('isIgnoredConsoleError')
    expect(realClickSmoke).toContain('net::ERR_CONNECTION_CLOSED')
    expect(realClickSmoke).toContain("message.type() === 'error'")
    expect(realClickSmoke).toContain('result.ignoredConsoleErrors.push')
    expect(realClickSmoke).toContain('result.consoleErrors.push')
    expect(realClickSmoke).toContain('ignoredConsoleErrorCount')
    expect(realClickSmoke).toContain("if (result.consoleErrors.length || result.pageErrors.length) result.status = 'FAIL'")
  })

  it('keeps real-login smoke non-fatal for route-switch fetch abort noise only', () => {
    expect(realLoginSmoke).toContain('ignoredConsoleErrors')
    expect(realLoginSmoke).toContain('isIgnoredConsoleError')
    expect(realLoginSmoke).toContain('TypeError: Failed to fetch')
    expect(realLoginSmoke).toContain('result.ignoredConsoleErrors.push')
    expect(realLoginSmoke).toContain('result.consoleErrors.push')
    expect(realLoginSmoke).toContain('ignoredConsoleErrorCount')
    expect(realLoginSmoke).toContain('result.status = \'FAIL\'')
    expect(realLoginSmoke).toContain('result.pageErrors.push')
  })

  it('verifies the order drawer photo access jump into the album workspace', () => {
    expect(realClickSmoke).toContain('assertOrderPhotoAccessJumpToAlbum')
    expect(realClickSmoke).toContain('frontendAlbumIds')
    expect(realClickSmoke).toContain('`ALB-${album.id}`')
    expect(realClickSmoke).toContain("getByRole('button', { name: '查看更多' })")
    expect(realClickSmoke).toContain('await moreButton.waitFor({ timeout: 15000 })')
    expect(realClickSmoke).not.toContain("await drawer.getByText('最近访问').waitFor({ timeout: 15000 })")
    expect(realClickSmoke).toContain("url.pathname === '/service/photos'")
    expect(realClickSmoke).toContain("frontendAlbumIds.includes(url.searchParams.get('album') || '')")
    expect(realClickSmoke).toContain('客片交付控制台')
    expect(realClickSmoke).toContain('new RegExp(`Roll · (${frontendAlbumIds')
    expect(realClickSmoke).toContain('photo-access-album-workspace')
    expect(realClickSmoke).toContain('photo-access-jump-to-album')
    expect(realClickSmoke).toContain('await page.goto(returnUrl')
  })

  it('captures actionable evidence when the reversible click smoke fails', () => {
    expect(realClickSmoke).toContain('failureEvidence: null')
    expect(realClickSmoke).toContain('captureFailureEvidence')
    expect(realClickSmoke).toContain("await screenshot(page, 'failure-page')")
    expect(realClickSmoke).toContain('visibleText')
    expect(realClickSmoke).toContain('result.network.slice(-12)')
    expect(realClickSmoke).toContain('currentUrl')
    expect(realClickSmoke).toContain('currentOrderStatus')
    expect(realClickSmoke).toContain('createdOrderNo')
    expect(realClickSmoke).toContain('## Failure Evidence')
    expect(realClickSmoke).toContain('await captureFailureEvidence(page, error)')
  })
})
